backend:
  name: git-gateway
  branch: main # Or master, or whatever your main branch is

media_folder: "static/images" # Where the CMS should save images
public_folder: "/images"

collections:
  - name: "products_for_sale"
    label: "Products for Sale"
    folder: "content/products-for-sale"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Tables", "Chairs", "Decorations", "Cabinets"] }
      - { label: "Price ($)", name: "price", widget: "number" }
      - { label: "Wood Type", name: "woodType", widget: "select", options: ["Oak", "Walnut", "Cedar", "Mahogany", "Mixed"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Featured on Homepage", name: "featured", widget: "boolean", default: false, hint: "Check this box to feature the product on the main page slider." }

  - name: "products_for_rent"
    label: "Products for Rent"
    folder: "content/products-for-rent"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }